spring.application.name=demo
# ── Servidor ──────────────────────────────────────────
server.port=8080

# ── MySQL ─────────────────────────────────────────────
spring.datasource.url=jdbc:mysql://localhost:3306/TankOfTitans
spring.datasource.username=admin_proyecto
spring.datasource.password=Complex_competencia
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ── JWT ─────────────────────────────────────────────
jwt.secret=clave_super_secreta_para_advanced_wars_larga_2026
jwt.expiration=86400000